apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: praxe2026
type: Opaque
data:
  root-password: Um9vdFBhc3MxIQ==   # RootPass1!
  username: ZGVtbzY3YWRtaW4=        # demo67admin
  password: RGVtbzY3UGFzczEh        # Demo67Pass1!
  database: ZGVtbzY3ZGI=            # demo67db
