apiVersion: apps/v1
kind: Deployment
metadata:
  name: dominik-mysql
  namespace: praxe2026
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dominik-mysql
  template:
    metadata:
      labels:
        app: dominik-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.4
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dominik-mysql-secret
                  key: root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: dominik-mysql-secret
                  key: database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: dominik-mysql-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dominik-mysql-secret
                  key: password
          volumeMounts:
            - name: mysql-data2
              mountPath: /var/lib/mysql
            - name: mysql-init2
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
                - -u
                - demo67admin
                - -pDemo67Pass1!
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: mysql-data2
          persistentVolumeClaim:
            claimName: dominik-mysql-pvc
        - name: mysql-init2
          configMap:
            name: dominik-mysql-init-sql
---
apiVersion: v1
kind: Service
metadata:
  name: dominik-mysql
  namespace: praxe2026
spec:
  selector:
    app: dominik-mysql
  ports:
    - port: 3306
      targetPort: 3306
