apiVersion: v1
kind: Config
clusters:
  - name: bacprac2026
    cluster:
      server: https://178.18.244.197:6443
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTnpNME1USTBPREl3SGhjTk1qWXdNekV6TVRRek5EUXlXaGNOTXpZd016RXdNVFF6TkRReQpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTnpNME1USTBPREl3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRMkJHZzM0ZWhBOUlNZWpSd0RZWVZhMlZ4aXRYc3lDOXdGN0t5Q3c3dDgKSkY0dFhqYkFvVXBETmFrNDZtOW5Rd1o1YkhnNmZwYi84RllBVHhKRUpNSWpvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUtOeHp1MUIzQVEwTE1icDZ3Tmo5CmZYTzRIdTh3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnQmVPTFhiR3FTTm1RWGIwZk9SZDV2RG5HdzhSKzdOS04KeFErTjBNamRjK2dDSUZ3UUFqMHpIZUNiaHJGS0ZEWStmTldaMXptenFsem82WjduNUNibERjK3AKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
contexts:
  - name: praxe-user-2@bacprac2026
    context:
      cluster: bacprac2026
      namespace: praxe2026
      user: praxe-user-2
current-context: praxe-user-2@bacprac2026
users:
  - name: praxe-user-2
    user:
      token: eyJhbGciOiJSUzI1NiIsImtpZCI6InhvR2xmSnBLdXNvQWxoRmw4cmlvYXI5UGRza29hYy1ueDlINlFoYVlsQjQifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJwcmF4ZTIwMjYiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoicHJheGUtdXNlci0yLXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InByYXhlLXVzZXItMiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImQ5NDc0MDZlLWYzNTUtNDQzNi1iZWUzLTY5YzUyZmVmMzc4MiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpwcmF4ZTIwMjY6cHJheGUtdXNlci0yIn0.iLHhePYVaKIWPT2CILoqYJ-dvTFhWiTcXUUjdM5vbQU1momaxfk2iy7Oeq7wfQlowO_JfM3gCeQehQ_4cyg8J3I1cCqrDEYHR6jy7fkTwnJLd_6_MzyP6F01M0jgqlfu92IVySqJyKu2yF_y0fkGOAqZnBdDtE-BVf96qeKMy8y02gPmTEHt4xKg4qHeBTHejc7MuKogzhmB-I2m998aQnZPmvzBviP_yUyMi7HMxInhxUJMmv_dS6clSCjYp5Dqf8t23elPh8xFIdLlTWafgVUxEGWnk93SaDNC2UagSZUg4_FU1Gst-eWtRlx5qBm3OsObqBZHXqoK5EzshdRfmA
